### ISSUE TITLE
loading files

### ISSUE THREAD

**Issue by sakurita17** [Foggalong/RobustOCS#24]
Hey @Foggalong ,

I'm encountering an issue while trying to load the .txt files. Despite having imported the necessary module :).

![image](https://github.com/user-attachments/assets/f3ce5a57-9753-44ec-b5af-30a03f0e6459)

Thanks for your help! 🙂
Jaime

**Comment by Foggalong** [comment]
@sakurita17 Huh, that's weird! If you open the file browser in the same location as `test.py` what do you see?

**Comment by sakurita17** [comment]
@Foggalong Here’s a screenshot of what I see in the file browser. Does this answer the question? right? 
![image](https://github.com/user-attachments/assets/6e5244e9-18c4-48db-9b0d-68ea5fbc2a41)

**Comment by Foggalong** [comment]
Ah yes, I see the issue! When you use VS Code to run `test.py` from your working directory

```bash
`~/Documents/GitHub/robust-genetics Copy2/
```

python runs that script _in_ your working directory, not in `test.py`'s location

```bash
`~/Documents/GitHub/robust-genetics Copy2/examples/50/
```

which is two levels deeper. Whether working with Python or similar languages like R or MATLAB, when you run code which involves path to files it always looks for them from your working directory, not from the location of the code.

These three `test.py` scripts you're trying to use are all designed to be ran from **their** location, i.e. the same folder as the data files. You can see this in the [GitHub workflow](https://github.com/Foggalong/RobustOCS/blob/main/.github/workflows/check-build.yml#L27-L44) which checks the build - the runner changes the working directory to the location of `test.py` each time.

In your case, `test.py` is looking for `EBV50.txt` in your working directory (where it's not found), rather than in the same location as `test.py` (where it actually is). See also [example.py](https://github.com/Foggalong/RobustOCS/blob/main/example.py#L7-L10) - it's designed to be run from the root of the GitHub repository, so includes explicit paths to the locations of the datafiles. If that's still a bit unclear you might find [this StackOverflow question](https://stackoverflow.com/questions/45591428/what-exactly-is-current-working-directory) helpful, where other people have given alternative explanations to a similar question :slightly_smiling_face:

**Comment by sakurita17** [comment]
> Ah yes, I see the issue! When you use VS Code to run `test.py` from your working directory
> 
> ```shell
> ~/Documents/GitHub/robust-genetics Copy2/
> ```
> 
> python runs that script _in_ your working directory, not in `test.py`'s location
> 
> ```shell
> ~/Documents/GitHub/robust-genetics Copy2/examples/50/
> ```
> 
> which is two levels deeper. Whether working with Python or similar languages like R or MATLAB, when you run code which involves path to files it always looks for them from your working directory, not from the location of the code.
> 
> These three `test.py` scripts you're trying to use are all designed to be ran from **their** location, i.e. the same folder as the data files. You can see this in the [GitHub workflow](https://github.com/Foggalong/RobustOCS/blob/main/.github/workflows/check-build.yml#L27-L44) which checks the build - the runner changes the working directory to the location of `test.py` each time.
> 
> In your case, `test.py` is looking for `EBV50.txt` in your working directory (where it's not found), rather than in the same location as `test.py` (where it actually is). See also [example.py](https://github.com/Foggalong/RobustOCS/blob/main/example.py#L7-L10) - it's designed to be run from the root of the GitHub repository, so includes explicit paths to the locations of the datafiles. If that's still a bit unclear you might find [this StackOverflow question](https://stackoverflow.com/questions/45591428/what-exactly-is-current-working-directory) helpful, where other people have given alternative explanations to a similar question 🙂

Thanks for the explanation @Foggalong . It seems to be already running. 
![image](https://github.com/user-attachments/assets/6390ed84-27de-4f8e-b77a-65399603e65c)
