### ISSUE TITLE
too many values to unpack

### ISSUE THREAD

**Issue by sakurita17** [Foggalong/RobustOCS#29]
Hi @Foggalong I have already updated robustocs, thank you.
![image](https://github.com/user-attachments/assets/b8263b0c-538b-4e84-848e-cdc0ce043613)

I tried rerunning examples 04 and 50 but encountered the following error. 
![image](https://github.com/user-attachments/assets/f5060739-4d91-4dad-a90a-b01c80e4142d)

What could I be doing wrong?

**Comment by Foggalong** [comment]
Hey @sakurita17! You've updated the module but not pulled the latest version of the repository. This means ROCS is 0.2, but the examples you're trying to use it with were written for 0.1! Anywhere in the repository you need to run

```bash
git pull
```

The specific error message is happening because `load_problem` now has additional return values corresponding to `sires`, `dams`, and candidate `names`. See the [documentation](https://github.com/Foggalong/RobustOCS/wiki/load_problem) for more info, there are examples of how to use the key functions 🙂

**Comment by sakurita17** [comment]
👍🏼

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
